#!/usr/bin/env python3
"""
Generate references/skill-inventory.md documenting:
  - user-authored skills copied into this repo (skills/)
  - external skill sources that bootstrap.sh re-links (.agents, .claude, .codegraph)
Reads no secret data. Safe to run any time.
"""
import os

HOME = os.path.expanduser("~/")
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SKILLS_DST = os.path.join(ROOT, "skills")

def list_dirs(path):
    if not os.path.isdir(path):
        return []
    return sorted(d for d in os.listdir(path)
                 if os.path.isdir(os.path.join(path, d)))

lines = ["# Skill Inventory", "",
         "Generated by scripts/inventory.py. Names only — no secret data.", ""]

# 1. user-authored skills bundled in this repo
lines += ["## User-authored skills (committed in skills/)", ""]
bundled = list_dirs(SKILLS_DST)
lines.append(f"Total: {len(bundled)}")
for name in bundled:
    lines.append(f"- {name}")
lines.append("")

# 2. external skill sources (symlinked on the source machine + captured in skills-external/)
sources = {
    ".agents/skills": "Agent-runtime skills (Claude/Codex/etc.) — captured in skills-external/",
    ".claude/skills": "Claude Code skills",
    ".codegraph": "CodeGraph skills",
}
lines += ["## External skill sources (re-linked by bootstrap.sh)", ""]
for rel, desc in sources.items():
    p = os.path.join(HOME, rel)
    if os.path.isdir(p):
        ext = list_dirs(p)
        lines.append(f"### {rel} — {desc}")
        lines.append(f"Total: {len(ext)}")
        for name in ext:
            lines.append(f"- {name}")
        lines.append("")
    else:
        lines.append(f"### {rel} — {desc}")
        lines.append("_not present on this machine_")
        lines.append("")

out = os.path.join(ROOT, "references", "skill-inventory.md")
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {out} ({len(bundled)} bundled skills documented)")
